In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("HTML_Top13_Features.csv")

# Ver primeras filas
df.head()

,file_name,url_punct_char_count,tag_count,whitespace_ratio,entropy,form_count,embedded_js_count,html_whitespace_ratio,script_entropy,min_link_length,external_link_count,total_script_characters,internal_link_count,url_digit_count,label
0,sample_09001.html,756,475,0.476933,5.072891,0,11,0.152737,4.906402,1,57,15762,39,109,0
1,sample_09002.html,287,82,0.356557,5.202024,0,3,0.179456,4.625064,21,8,2543,27,130,0
2,sample_09003.html,667,406,0.390225,5.164168,1,10,0.149810,4.220362,9,80,7163,26,333,0
3,sample_09004.html,1204,321,0.534781,5.671159,0,33,0.025707,5.626662,17,74,268250,2,1013,0
4,sample_09005.html,2606,665,0.441595,5.136624,5,8,0.130050,5.462992,8,243,7666,8,924,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19997 entries, 0 to 19996
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   file_name                19997 non-null  object
 1   url_punct_char_count     19997 non-null  int64
 2   tag_count                19997 non-null  int64
 3   whitespace_ratio         19997 non-null  float64
 4   entropy                  19997 non-null  float64
 5   form_count               19997 non-null  int64
 6   embedded_js_count        19997 non-null  int64
 7   html_whitespace_ratio    19997 non-null  float64
 8   script_entropy           19997 non-null  float64
 9   min_link_length          19997 non-null  int64
 10  external_link_count      19997 non-null  int64
 11  total_script_characters  19997 non-null  int64
 12  internal_link_count      19997 non-null  int64
 13  url_digit_count          19997 non-null  int64
 14  label                    19997 non-null  int64
dtypes: float64(4), int64(10), object(1)
memory usage: 2.3+ MB

In [5]:
df.describe()

,url_punct_char_count,tag_count,whitespace_ratio,entropy,form_count,embedded_js_count,html_whitespace_ratio,script_entropy,min_link_length,external_link_count,total_script_characters,internal_link_count,url_digit_count,label
count,19997.000000,19997.000000,19997.000000,19997.000000,19997.000000,19997.000000,19997.000000,19997.000000,19997.000000,19997.000000,1.999700e+04,19997.000000,19997.000000,19997.000000
mean,884.284093,483.913637,0.371615,5.166407,1.319648,7.261689,0.118302,4.116942,20.723359,55.149622,2.313485e+04,55.626544,742.790119,0.500025
std,3466.036814,984.328387,0.164450,0.387730,2.833063,12.329298,0.076159,2.050831,686.987243,119.753444,8.233276e+04,169.391932,6484.590670,0.500013
min,0.000000,3.000000,0.000000,0.914438,0.000000,0.000000,0.000009,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,47.000000,57.000000,0.286301,4.991718,0.000000,1.000000,0.070555,4.356263,1.000000,1.000000,2.370000e+02,3.000000,11.000000,0.000000
50%,265.000000,182.000000,0.396039,5.179042,1.000000,3.000000,0.108181,5.042327,1.000000,16.000000,2.774000e+03,11.000000,99.000000,1.000000
75%,1037.000000,600.000000,0.487342,5.354134,2.000000,9.000000,0.149205,5.366036,11.000000,66.000000,1.162600e+04,46.000000,422.000000,1.000000
max,283826.000000,43591.000000,0.854354,7.874702,189.000000,333.000000,0.830095,6.274234,77698.000000,5550.000000,2.506028e+06,6190.000000,604256.000000,1.000000

In [6]:
df.columns

Index(['file_name', 'url_punct_char_count', 'tag_count', 'whitespace_ratio',
       'entropy', 'form_count', 'embedded_js_count', 'html_whitespace_ratio',
       'script_entropy', 'min_link_length', 'external_link_count',
       'total_script_characters', 'internal_link_count', 'url_digit_count',
       'label'],
      dtype='object')

In [8]:
target_col = "label" 

df[target_col].value_counts()

label
1    9999
0    9998
Name: count, dtype: int64

El dataset esta balanceado